### ISSUE TITLE
Releases should contain a static openrpc.json

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/api-specs#107]
Having a link to the post-processed openrpc.json makes it a lot easier to use.

**Comment by shanejonas** [comment]
this repo is deployed via gh pages, heres the link: https://metamask.github.io/api-specs/latest/metamask-openrpc.json

we could still add it as an artifact, but would require changes in the gh action [here](https://github.com/MetaMask/action-publish-release/blob/main/scripts/create-github-release.sh#L19-L22).
