### ISSUE TITLE
How to recover some tokens from one network to another via MetaMask API.

### ISSUE THREAD

**Issue by zydjohnHotmail** [MetaMask/api-specs#111]
Hello:
I have an issue which I want to solve it by MetaMask API, but before I spend more time on this topic, please provide some advice.
A few weeks ago, I sent some cryptocurrency tokens (Ruff Chain) from one exchange to another exchange. Unfortunately, even the sender’s exchange shows the successful sending, but the only network for sending this token on the sender’s exchange is on HECO network, but the receiver’s deposit address can receive the same token using only ERC20 network.
So those sent tokens stayed in the network for more than one month. The receiver’s exchange has recently released some kind of token recovery tools, so I can recover those tokens sent to my deposit address using ERC20 network. But I have to pay 100USDT each time if I use their tools.
I want to know if I can write some code (JavaScript) to do the similar job?
Or, if it is not easy to do this, then, can I use MetaMask wallet to receive similar tokens, which the sending network and the receiving network don’t match, thus cause the tokens not reaching their deposit addresses forever.  If I can use MetaMask wallet to receive those tokens first, then change their network, then send them again from MetaMask wallet using the same network as the receiver’s deposits address network.  That is changing from HECO network to REC20 network.
If not possible, then let me know, I will pay the fee to use the receiver’s exchange tools to recover my tokens.
If possible, please give some general ideas on how I can do this or provide some further readings on this topic.  I can do this by hand for a few times, if possible, but I wish to be able to do this more via API, since there could be more chances to use this API functions.
Thanks,

**Comment by vandan** [comment]
Please try our Discord channel for general support: https://discord.gg/consensys
